# Generated by Django 4.2.18 on 2025-07-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('title', models.CharField(max_length=200, verbose_name='職種・肩書き')),
                ('bio', models.TextField(verbose_name='自己紹介')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='居住地')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='プロフィール画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロフィール',
                'verbose_name_plural': 'プロフィール',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frontend', 'フロントエンド'), ('backend', 'バックエンド'), ('infrastructure', 'インフラ'), ('database', 'データベース'), ('framework', 'フレームワーク'), ('cloud', 'クラウド'), ('tools', 'ツール'), ('other', 'その他')], max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'スキルカテゴリ',
                'verbose_name_plural': 'スキルカテゴリ',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='スキル名')),
                ('experience_years', models.IntegerField(verbose_name='経験年数')),
                ('proficiency', models.IntegerField(choices=[(1, '初級'), (2, '中級'), (3, '上級'), (4, 'エキスパート')], verbose_name='習熟度')),
                ('description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skillcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'スキル',
                'verbose_name_plural': 'スキル',
                'ordering': ['category', '-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('project_type', models.CharField(choices=[('web', 'Webアプリケーション'), ('mobile', 'モバイルアプリ'), ('desktop', 'デスクトップアプリ'), ('api', 'API'), ('landing', 'ランディングページ'), ('other', 'その他')], max_length=20, verbose_name='種類')),
                ('description', models.TextField(verbose_name='説明')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='プロジェクト画像')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('technologies', models.TextField(verbose_name='使用技術')),
                ('created_date', models.DateField(verbose_name='作成日')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_featured', models.BooleanField(default=False, verbose_name='注目作品')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'ordering': ['-is_featured', 'display_order', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='GitHub ユーザー名')),
                ('repositories_count', models.IntegerField(default=0, verbose_name='リポジトリ数')),
                ('followers_count', models.IntegerField(default=0, verbose_name='フォロワー数')),
                ('following_count', models.IntegerField(default=0, verbose_name='フォロー数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_profile', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'GitHubプロフィール',
                'verbose_name_plural': 'GitHubプロフィール',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案件名')),
                ('company', models.CharField(max_length=100, verbose_name='会社名')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('is_current', models.BooleanField(default=False, verbose_name='現在も継続中')),
                ('description', models.TextField(verbose_name='案件内容')),
                ('role', models.CharField(max_length=100, verbose_name='役割')),
                ('team_size', models.IntegerField(verbose_name='チーム規模')),
                ('technologies', models.TextField(verbose_name='使用技術')),
                ('processes', models.CharField(max_length=200, verbose_name='担当工程')),
                ('achievements', models.TextField(blank=True, verbose_name='成果・実績')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profile')),
            ],
            options={
                'verbose_name': '経歴',
                'verbose_name_plural': '経歴',
                'ordering': ['-start_date'],
            },
        ),
    ]
