# Generated by Django 4.2.18 on 2025-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_profile_linkedin_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='アカウント作成日'),
        ),
        migrations.AddField(
            model_name='githubprofile',
            name='gists_count',
            field=models.IntegerField(default=0, verbose_name='Gist数'),
        ),
        migrations.AddField(
            model_name='githubprofile',
            name='github_bio',
            field=models.TextField(blank=True, default='', verbose_name='GitHub Bio'),
        ),
        migrations.AddField(
            model_name='githubprofile',
            name='github_blog',
            field=models.URLField(blank=True, default='', verbose_name='GitHub Blog URL'),
        ),
        migrations.AddField(
            model_name='githubprofile',
            name='github_location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='GitHub 居住地'),
        ),
    ]
