# Generated by Django 4.2.18 on 2025-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_githubprofile_created_at_githubprofile_gists_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubprofile',
            name='language_stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='言語統計'),
        ),
    ]
