# Generated by Django 4.2.18 on 2025-07-15 16:10

from django.db import migrations


def fix_github_fields(apps, schema_editor):
    GitHubProfile = apps.get_model('portfolio', 'GitHubProfile')
    for profile in GitHubProfile.objects.all():
        updated = False
        if profile.github_bio is None:
            profile.github_bio = ''
            updated = True
        if profile.github_location is None:
            profile.github_location = ''
            updated = True
        if profile.github_blog is None:
            profile.github_blog = ''
            updated = True
        if updated:
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_githubprofile_language_stats'),
    ]

    operations = [
        migrations.RunPython(fix_github_fields),
    ]
