# Generated by Django 4.2.18 on 2025-07-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20250716_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
