# Generated by Django 4.2.18 on 2025-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_experience_company_remove_skill_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_domains',
            field=models.TextField(blank=True, help_text='例：金融系, EC系, 業務システムなど', verbose_name='得意業務'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('prefer_not_to_say', '回答しない')], max_length=20, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skilled_technologies',
            field=models.TextField(blank=True, help_text='例：Python, Django, API実装など', verbose_name='得意技術'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialties',
            field=models.TextField(blank=True, help_text='例：Webアプリケーション開発, API開発, バッチ処理など', verbose_name='得意分野'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name='自己PR'),
        ),
    ]
