# Generated by Django 4.2.18 on 2025-08-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profile_age_profile_business_domains_profile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='technologies',
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements_learnings',
            field=models.TextField(blank=True, default='', help_text='Markdown記法対応', verbose_name='成果・学び'),
        ),
        migrations.AddField(
            model_name='experience',
            name='business_content',
            field=models.TextField(default='', help_text='Markdown記法対応', verbose_name='業務内容'),
        ),
        migrations.AddField(
            model_name='experience',
            name='databases',
            field=models.TextField(blank=True, verbose_name='DB'),
        ),
        migrations.AddField(
            model_name='experience',
            name='frameworks_tools',
            field=models.TextField(blank=True, verbose_name='FW・MWツール等'),
        ),
        migrations.AddField(
            model_name='experience',
            name='process_basic_design',
            field=models.BooleanField(default=False, verbose_name='基本設計'),
        ),
        migrations.AddField(
            model_name='experience',
            name='process_detail_design',
            field=models.BooleanField(default=False, verbose_name='詳細設計'),
        ),
        migrations.AddField(
            model_name='experience',
            name='process_implementation',
            field=models.BooleanField(default=False, verbose_name='実装'),
        ),
        migrations.AddField(
            model_name='experience',
            name='process_maintenance',
            field=models.BooleanField(default=False, verbose_name='保守運用'),
        ),
        migrations.AddField(
            model_name='experience',
            name='process_requirement',
            field=models.BooleanField(default=False, verbose_name='要件定義'),
        ),
        migrations.AddField(
            model_name='experience',
            name='process_testing',
            field=models.BooleanField(default=False, verbose_name='テスト'),
        ),
        migrations.AddField(
            model_name='experience',
            name='programming_languages',
            field=models.TextField(blank=True, verbose_name='使用言語'),
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(default='', help_text='Markdown記法対応', verbose_name='担当業務'),
        ),
        migrations.AddField(
            model_name='experience',
            name='server_os',
            field=models.TextField(blank=True, verbose_name='サーバOS'),
        ),
    ]
