# Generated by Django 4.2.18 on 2025-08-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_experience_achievements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-is_featured', '-experience_years'], 'verbose_name': 'スキル', 'verbose_name_plural': 'スキル'},
        ),
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='得意スキル'),
        ),
    ]
