# Generated by Django 4.2.18 on 2025-08-15 01:33

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_skill_options_skill_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=portfolio.models.safe_upload_to_avatars, verbose_name='プロフィール画像'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.safe_upload_to_projects, verbose_name='プロジェクト画像'),
        ),
    ]
