# Generated by Django 4.2.18 on 2025-08-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_profile_avatar_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='business_content',
            field=models.TextField(blank=True, default='', help_text='Markdown記法対応', verbose_name='業務内容'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(blank=True, default='', help_text='Markdown記法対応', verbose_name='担当業務'),
        ),
    ]
