# Generated by Django 4.2.18 on 2025-08-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_experience_business_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='achievements_learnings',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='responsibilities',
        ),
    ]
