# Generated by Django 4.2.18 on 2025-08-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_experience_achievements_learnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_domains',
        ),
    ]
